name: mkdocs-quarto-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - r-base # For R support
  - r-tidyverse # For read_csv, dplyr functions in R code
  - quarto
  - pip:
    - mkdocs # The core MkDocs static site generator
    - mkdocs-material # The theme specified in mkdocs.yml
    - mkquartodocs # The plugin to handle Quarto files